name: Test and Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1

    - name: 'Lint'
      run: |
          dub fetch dfmt 
          dub build dfmt
          dub run dfmt -- source/
    - name: 'Build and Test'
      run:  |
        dub build --compiler=$DC
        dub test --compiler=$DC
