name: unittest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: mihails-strasuns/setup-dlang@v0
    - name: Test
      run: dub test
