name: Test and Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest- 
    - name: Lint
      run: dfmt source/
    - name: Test
      run: dub test
